import type { Instrument } from "./types";

// 楽器マスターデータ（図鑑・クイズ共通）
// glyph: 表示用絵文字 / hasImage: 専用絵文字があり画像・シルエットクイズに使える
export const INSTRUMENTS: Instrument[] = [
  // ===== 弦楽器 =====
  {
    id: "violin",
    name: "バイオリン",
    reading: "ばいおりん",
    category: "strings",
    glyph: "🎻",
    hasImage: true,
    description: "弦楽器の花形。高い音域を担当し、オーケストラの主旋律を奏でることが多い。",
    fact: "標準的なバイオリンの弦は4本（G・D・A・E）。",
  },
  {
    id: "viola",
    name: "ビオラ",
    reading: "びおら",
    category: "strings",
    glyph: "🎻",
    hasImage: false,
    description: "バイオリンよりひと回り大きく、低めで深みのある音色を持つ弦楽器。",
    fact: "バイオリンより5度低く調弦される（C・G・D・A）。",
  },
  {
    id: "cello",
    name: "チェロ",
    reading: "ちぇろ",
    category: "strings",
    glyph: "🎻",
    hasImage: false,
    description: "床にエンドピンを立てて演奏する大型の弦楽器。豊かな中低音が魅力。",
    fact: "人間の声に最も近い音域を持つと言われる。",
  },
  {
    id: "contrabass",
    name: "コントラバス",
    reading: "こんとらばす",
    category: "strings",
    glyph: "🎻",
    hasImage: false,
    description: "弦楽器の中で最も大きく、最も低い音を出す。立って、または高い椅子で演奏する。",
    fact: "ジャズではウッドベースとも呼ばれる。",
  },
  {
    id: "guitar",
    name: "ギター",
    reading: "ぎたー",
    category: "strings",
    glyph: "🎸",
    hasImage: true,
    description: "6本の弦を指やピックで弾く撥弦楽器。クラシックからロックまで幅広く活躍。",
    fact: "標準的なギターの弦は6本。",
  },
  {
    id: "harp",
    name: "ハープ",
    reading: "はーぷ",
    category: "strings",
    glyph: "🎵",
    hasImage: false,
    description: "三角形のフレームに多数の弦を張った優雅な弦楽器。ペダルで半音を変える。",
    fact: "コンサートハープの弦は47本前後ある。",
  },
  {
    id: "banjo",
    name: "バンジョー",
    reading: "ばんじょー",
    category: "strings",
    glyph: "🪕",
    hasImage: true,
    description: "丸い太鼓状の胴を持つ撥弦楽器。明るく歯切れのよい音色。",
    fact: "カントリーやブルーグラスで欠かせない楽器。",
  },
  {
    id: "ukulele",
    name: "ウクレレ",
    reading: "うくれれ",
    category: "strings",
    glyph: "🎸",
    hasImage: false,
    description: "ハワイ生まれの小型の撥弦楽器。4本の弦を持つ。",
    fact: "ポルトガルの楽器がハワイに伝わって生まれた。",
  },

  // ===== 管楽器 =====
  {
    id: "flute",
    name: "フルート",
    reading: "ふるーと",
    category: "winds",
    glyph: "🪈",
    hasImage: true,
    description: "横に構えて吹く金属製の木管楽器。澄んだ高音が特徴。",
    fact: "リードを使わず、息を吹き当てて音を出すエアリード楽器。",
  },
  {
    id: "clarinet",
    name: "クラリネット",
    reading: "くらりねっと",
    category: "winds",
    glyph: "🎵",
    hasImage: false,
    description: "1枚のリードで音を出す木管楽器。幅広い音域と柔らかい音色を持つ。",
    fact: "シングルリード楽器の代表格。",
  },
  {
    id: "saxophone",
    name: "サックス",
    reading: "さっくす",
    category: "winds",
    glyph: "🎷",
    hasImage: true,
    description: "金属製だがリードで鳴らすため木管楽器に分類される。ジャズの花形。",
    fact: "発明者アドルフ・サックスの名にちなむ。",
  },
  {
    id: "oboe",
    name: "オーボエ",
    reading: "おーぼえ",
    category: "winds",
    glyph: "🎵",
    hasImage: false,
    description: "2枚のリードを使うダブルリードの木管楽器。哀愁のある音色。",
    fact: "オーケストラのチューニングの基準音(A)を出す役割を担う。",
  },
  {
    id: "fagotto",
    name: "ファゴット",
    reading: "ふぁごっと",
    category: "winds",
    glyph: "🎵",
    hasImage: false,
    description: "ダブルリードの低音木管楽器。バスーンとも呼ばれる。",
    fact: "長い管を二つ折りにした構造を持つ。",
  },
  {
    id: "trumpet",
    name: "トランペット",
    reading: "とらんぺっと",
    category: "winds",
    glyph: "🎺",
    hasImage: true,
    description: "3つのバルブを持つ金管楽器。輝かしく力強い高音を出す。",
    fact: "金管楽器では最も高い音域を担当することが多い。",
  },
  {
    id: "trombone",
    name: "トロンボーン",
    reading: "とろんぼーん",
    category: "winds",
    glyph: "🎺",
    hasImage: false,
    description: "スライドを伸縮させて音程を変える金管楽器。",
    fact: "バルブではなくスライドで音程を作る珍しい金管楽器。",
  },
  {
    id: "horn",
    name: "ホルン",
    reading: "ほるん",
    category: "winds",
    glyph: "🎺",
    hasImage: false,
    description: "渦を巻いた管と朝顔を持つ金管楽器。柔らかく温かい音色。",
    fact: "右手をベルに入れて音色を調整する。",
  },
  {
    id: "tuba",
    name: "チューバ",
    reading: "ちゅーば",
    category: "winds",
    glyph: "🎺",
    hasImage: false,
    description: "金管楽器の中で最も大きく、最も低い音を支える。",
    fact: "吹奏楽やオーケストラの低音の土台を担う。",
  },
  {
    id: "recorder",
    name: "リコーダー",
    reading: "りこーだー",
    category: "winds",
    glyph: "🪈",
    hasImage: false,
    description: "縦に構えて吹く木管楽器。学校教育でもおなじみ。",
    fact: "ソプラノ・アルトなど大きさの違う種類がある。",
  },

  // ===== 打楽器 =====
  {
    id: "snaredrum",
    name: "スネアドラム",
    reading: "すねあどらむ",
    category: "percussion",
    glyph: "🥁",
    hasImage: true,
    description: "裏面に響き線(スナッピー)を張った小太鼓。歯切れのよい音が特徴。",
    fact: "響き線が独特のザラっとした響きを生む。",
  },
  {
    id: "timpani",
    name: "ティンパニ",
    reading: "てぃんぱに",
    category: "percussion",
    glyph: "🥁",
    hasImage: false,
    description: "釜形の胴を持つ大太鼓。ペダルで音程を変えられる。",
    fact: "打楽器の中でも明確な音程を出せる珍しい楽器。",
  },
  {
    id: "marimba",
    name: "マリンバ",
    reading: "まりんば",
    category: "percussion",
    glyph: "🎵",
    hasImage: false,
    description: "木製の音板を並べ、マレットで叩く鍵盤打楽器。温かく丸い音色。",
    fact: "音板の下の共鳴管が音を豊かに響かせる。",
  },
  {
    id: "xylophone",
    name: "シロフォン",
    reading: "しろふぉん",
    category: "percussion",
    glyph: "🎵",
    hasImage: false,
    description: "木琴の一種で、マリンバより高く硬い音色を持つ鍵盤打楽器。",
    fact: "ギリシャ語で「木の音」を意味する。",
  },
  {
    id: "cymbals",
    name: "シンバル",
    reading: "しんばる",
    category: "percussion",
    glyph: "🥁",
    hasImage: false,
    description: "2枚の金属円盤を打ち合わせる打楽器。華やかなクライマックスを彩る。",
    fact: "合わせシンバルとサスペンドシンバルがある。",
  },
  {
    id: "triangle",
    name: "トライアングル",
    reading: "とらいあんぐる",
    category: "percussion",
    glyph: "🔔",
    hasImage: false,
    description: "三角形の金属棒を叩く小型打楽器。澄んだ高い余韻が美しい。",
    fact: "片側が開いた三角形で、自由に響くようになっている。",
  },
  {
    id: "marakas",
    name: "マラカス",
    reading: "まらかす",
    category: "percussion",
    glyph: "🪇",
    hasImage: true,
    description: "中に粒を入れた振り鳴らす打楽器。ラテン音楽でおなじみ。",
    fact: "もとはひょうたんの中に種を入れて作られた。",
  },
  {
    id: "djembe",
    name: "ジャンベ",
    reading: "じゃんべ",
    category: "percussion",
    glyph: "🪘",
    hasImage: true,
    description: "西アフリカ生まれの片面太鼓。手で叩いて多彩な音を出す。",
    fact: "ゴブレット型の胴が特徴。",
  },

  // ===== 鍵盤楽器 =====
  {
    id: "piano",
    name: "ピアノ",
    reading: "ぴあの",
    category: "keyboard",
    glyph: "🎹",
    hasImage: true,
    description: "ハンマーで弦を打って音を出す鍵盤楽器。広い音域と表現力を持つ。",
    fact: "標準的な鍵盤数は88鍵。",
  },
  {
    id: "accordion",
    name: "アコーディオン",
    reading: "あこーでぃおん",
    category: "keyboard",
    glyph: "🪗",
    hasImage: true,
    description: "蛇腹で送った空気でリードを鳴らす鍵盤楽器。持ち運んで演奏できる。",
    fact: "蛇腹(ベローズ)の開閉で空気を送る。",
  },
  {
    id: "organ",
    name: "オルガン",
    reading: "おるがん",
    category: "keyboard",
    glyph: "🎹",
    hasImage: false,
    description: "パイプに空気を送って音を出す鍵盤楽器。壮大な響きを持つ。",
    fact: "パイプオルガンは「楽器の王様」と呼ばれる。",
  },
  {
    id: "harpsichord",
    name: "チェンバロ",
    reading: "ちぇんばろ",
    category: "keyboard",
    glyph: "🎹",
    hasImage: false,
    description: "弦をはじいて音を出す鍵盤楽器。バロック音楽で活躍した。",
    fact: "ピアノが普及する前の主要な鍵盤楽器だった。",
  },

  // ===== 民族楽器 =====
  {
    id: "shamisen",
    name: "三味線",
    reading: "しゃみせん",
    category: "ethnic",
    glyph: "🎵",
    hasImage: false,
    description: "日本の三弦の撥弦楽器。バチで弾いて演奏する。",
    fact: "胴には猫や犬の皮、近年は合成皮も使われる。",
  },
  {
    id: "erhu",
    name: "二胡",
    reading: "にこ",
    category: "ethnic",
    glyph: "🎵",
    hasImage: false,
    description: "中国の二弦の擦弦楽器。弓を弦の間に通して弾く。",
    fact: "弦は2本だけだが歌うような表現力を持つ。",
  },
  {
    id: "sitar",
    name: "シタール",
    reading: "したーる",
    category: "ethnic",
    glyph: "🎵",
    hasImage: false,
    description: "インドの撥弦楽器。多数の共鳴弦が独特の余韻を生む。",
    fact: "演奏弦の下に共鳴弦が張られている。",
  },
  {
    id: "koto",
    name: "琴",
    reading: "こと",
    category: "ethnic",
    glyph: "🎵",
    hasImage: false,
    description: "日本の伝統的な弦楽器。柱(じ)を動かして調弦する。",
    fact: "一般的な箏(そう)の弦は13本。",
  },
  {
    id: "bagpipe",
    name: "バグパイプ",
    reading: "ばぐぱいぷ",
    category: "ethnic",
    glyph: "🎵",
    hasImage: false,
    description: "袋に空気をためて鳴らす管楽器。スコットランドで有名。",
    fact: "持続的に鳴り続けるドローン音が特徴。",
  },
  {
    id: "didgeridoo",
    name: "ディジュリドゥ",
    reading: "でぃじゅりどぅ",
    category: "ethnic",
    glyph: "🎵",
    hasImage: false,
    description: "オーストラリア先住民の管楽器。長い木の筒を吹いて低音を出す。",
    fact: "循環呼吸という奏法で音を途切れさせず出す。",
  },
  {
    id: "panflute",
    name: "パンフルート",
    reading: "ぱんふるーと",
    category: "ethnic",
    glyph: "🎵",
    hasImage: false,
    description: "長さの違う管を束ねた笛。南米アンデスでおなじみ。",
    fact: "管の長さの違いで音程が決まる。",
  },
  {
    id: "ocarina",
    name: "オカリナ",
    reading: "おかりな",
    category: "ethnic",
    glyph: "🪈",
    hasImage: false,
    description: "土や陶器で作られた卵形の笛。やわらかく素朴な音色。",
    fact: "イタリア語で「小さなガチョウ」を意味する。",
  },
  {
    id: "castanets",
    name: "カスタネット",
    reading: "かすたねっと",
    category: "ethnic",
    glyph: "🎵",
    hasImage: false,
    description: "貝殻状の木片を打ち合わせる打楽器。スペイン舞踊で活躍。",
    fact: "フラメンコのリズムに欠かせない。",
  },
  {
    id: "tambourine",
    name: "タンバリン",
    reading: "たんばりん",
    category: "percussion",
    glyph: "🥁",
    hasImage: false,
    description: "枠に小さな金属円盤を付けた打楽器。振っても叩いても鳴る。",
    fact: "金属円盤はジングルと呼ばれる。",
  },
];

export const INSTRUMENT_BY_ID: Record<string, Instrument> = Object.fromEntries(
  INSTRUMENTS.map((i) => [i.id, i]),
);

export const CATEGORY_LABEL: Record<Instrument["category"], string> = {
  strings: "弦楽器",
  winds: "管楽器",
  percussion: "打楽器",
  keyboard: "鍵盤楽器",
  ethnic: "民族楽器",
};

export const IMAGE_INSTRUMENTS = INSTRUMENTS.filter((i) => i.hasImage);
